apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer  # set the type of Service
  selector:
    app: frontend     # referencing the Pod's label
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend     # needs to be the same as Service's selector
spec:
  containers:
  - name: frontend
    image: iivanov21/front-end-service:latest
    ports:
    - containerPort: 8081